# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package definition and tsconfig first for dependencies
COPY package.json tsconfig.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Default environment
ENV NODE_ENV=production

# Use stdio entrypoint
ENTRYPOINT ["node", "dist/index.js"]
